on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.x"

      - name: Install dependencies
        run: bun install

      - name: Run all tests
        run: mkdir -p data && bun test
